name: Deploy
on: [push]
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        env:
          DOCKER_BUILDKIT: "1"
        with:
          gcloud_service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          registry: europe-north1-docker.pkg.dev
          project_id: emilbroman
          image_name: website
          image_tag: latest,${{ github.sha }}
